name: Deploy

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        echo "$KNOWN_HOSTS" > known_hosts
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-18-206-119-195.compute-1.amazonaws.com "sudo bash ~/deploy.sh"
           

